base: &base
  adapter: postgresql
  encoding: utf8
  username:
  password: qwer213
  host: 127.0.0.1
  pool: 5

development:
  <<: *base
  database: sasta_price_developement

test:
  <<: *base
  database: sasta_price_developement

staging:
  <<: *base
  database: sasta_price_developement

production:
  <<: *base
  database: sasta_price_developement
